version: "3"

services:
  site:
    image: "docker.pkg.github.com/garage-isep/wsgit/wsgit:main" 
    container_name: "wsgit"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wsgit-secure.rule=Host(`wsgit.garageisep.com`)"
      - "traefik.http.routers.wsgit-secure.entrypoints=websecure"
      - "traefik.http.routers.wsgit-secure.tls.certresolver=myhttpchallenge"
      # https redirection
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wsgit.rule=Host(`wsjava.garageisep.com`)"
      - "traefik.http.routers.wsgit.entrypoints=web"
      - "traefik.http.routers.wsgit.middlewares=redirect"

networks:
  traefik:
    external: true