version: "3"

services:
  site:
    image: "docker.pkg.github.com/garage-isep/wsjava/wsjava:main" 
    container_name: "wsjava"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wsjava-secure.rule=Host(`wsjava.garageisep.com`)"
      - "traefik.http.routers.wsjava-secure.entrypoints=websecure"
      - "traefik.http.routers.wsjava-secure.tls.certresolver=myhttpchallenge"
      # https redirection
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wsjava.rule=Host(`wsjava.garageisep.com`)"
      - "traefik.http.routers.wsjava.entrypoints=web"
      - "traefik.http.routers.wsjava.middlewares=redirect"

networks:
  traefik:
    external: true
